/*
* Created on 2019-07-15
*/

#ifndef IFP_STRING_CONSTANTS_HEADER
#define IFP_STRING_CONSTANTS_HEADER

const char* IFP_SYMBOL_FILE_HEADER = 
"# This file has been generated by the InterFLOP sample to hold the symbols used by the given program.\n"
"# You can use it as a whitelist, blacklist, and modify it as you wish.\n"
"# Comments start with the character \'#\'.\n"
"# Each line of this file holds a symbol in the following format : \n \t\t\tmodule!symbol\n"
"# Here, a module can designate an executable, a library file... as per DynamoRIO's standards.\n"
"# A name alone (without a \'!\') designates the whole module\n\n";

const char* IFP_HELP_STRING =
"InterFLOP sample for DynamoRIO : replaces the floating point operations with their equivalent in Monte Carlo arithmetics [Parker et al. 2000]\n" 
"Usage : drrun [drrun options] -c libinterflop.so [interflop options] -- programToInstrument [program arguments]\n"
"Interflop options :\n"
"\t -h\n\t --help\n\t Displays the current help, stops the program\n\n"
"\t -n\n\t --no-lookup \n\t\t(Default) Disables the lookup for the symbols, instruments every floating operation\n\n"
"\t -w [filename]\n\t --whitelist [filename] \n\t\tInstruments only the symbols present in the given file\n\n"
"\t -b [filename]\n\t --blacklist [filename] \n\t\tDisable the instrumentation for the symbols present in the given file\n\n"
"\t -g\n\t --generate\n\t Generates the list of symbols in the given program, doesn't instrument anything\n\n"
"\n";
#endif